'use client';

import { ChangeEvent, useEffect, useMemo, useState } from 'react';
import { Camera, Cat, Globe2, Home, Plus, RefreshCw, Sparkles, Sticker, UserRound } from 'lucide-react';

const breeds=[['Bengal','孟加拉貓','🐆'],['British Shorthair','英國短毛貓','🩶'],['Maine Coon','緬因貓','🦁'],['Ragdoll','布偶貓','🤍'],['Siamese','暹羅貓','💎'],['Abyssinian','阿比西尼亞貓','🧡'],['Russian Blue','俄羅斯藍貓','🌫️'],['Sphynx','斯芬克斯貓','🌸'],['Norwegian Forest','挪威森林貓','🌲'],['Scottish Fold','蘇格蘭摺耳貓','🍪'],['Persian','波斯貓','☁️'],['Domestic Shorthair','米克斯／家貓','🌈']];
const incoming=[{name:'Mochi',breed:'British Shorthair',place:'Tokyo, Japan',emoji:'🐱',tag:'SLEEPY'},{name:'Nori',breed:'Maine Coon',place:'Helsinki, Finland',emoji:'😺',tag:'FLOOF'},{name:'豆花',breed:'Domestic Shorthair',place:'Kaohsiung, Taiwan',emoji:'😽',tag:'BLEP'}];
type Tab='home'|'dex'|'snap'|'collection'|'profile';
type MyCat={name:string;breed:string;place:string;photo?:string};

export default function Page(){
 const [tab,setTab]=useState<Tab>('home'),[swapped,setSwapped]=useState(false),[match,setMatch]=useState(0),[photo,setPhoto]=useState('');
 const [cats,setCats]=useState<MyCat[]>([{name:'Lucy',breed:'Bengal',place:'Taiwan'}]);
 const [draft,setDraft]=useState<MyCat>({name:'',breed:'Domestic Shorthair',place:'Taiwan'}),[adding,setAdding]=useState(false);
 const [saved,setSaved]=useState<string[]>([]); const active=cats[0]; const today=incoming[match];
 useEffect(()=>{try{const c=localStorage.getItem('catdex-cats'),s=localStorage.getItem('catdex-saved');if(c)setCats(JSON.parse(c));if(s)setSaved(JSON.parse(s));}catch{}},[]);
 const discovered=useMemo(()=>new Set(['Bengal','British Shorthair','Maine Coon','Domestic Shorthair',...cats.map(c=>c.breed)]),[cats]);
 function persist(next:MyCat[]){setCats(next);localStorage.setItem('catdex-cats',JSON.stringify(next))}
 function choosePhoto(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setPhoto(String(r.result));r.readAsDataURL(f)}
 function saveIncoming(){const next=Array.from(new Set([...saved,today.name]));setSaved(next);localStorage.setItem('catdex-saved',JSON.stringify(next));setTab('collection')}
 return <main className="app"><header><div className="brand"><span className="brandMark">C</span><b>CatDex</b></div><div className="streak">🔥 7</div></header>
 {tab==='home'&&<section className="screen"><div className="hello"><div><span className="eyebrow">HELLO, CAT PERSON</span><h1>今天要遇見哪隻貓？</h1><p>每天一張真實貓咪貼紙，和世界上的陌生貓友交換。</p></div><div className="avatar">{active?.photo?<img src={active.photo} alt="my cat"/>:'🐆'}</div></div><button className="daily" onClick={()=>setTab('snap')}><div className="camera"><Camera size={28}/></div><div><b>Today's Cat</b><span>拍下今天的 {active?.name||'貓咪'}</span></div><span className="arrow">›</span></button><div className="sectionTitle"><h2>World CatDex</h2><button onClick={()=>setTab('dex')}>查看全部</button></div><div className="progressCard"><div className="ring"><b>{discovered.size}</b><span>/ 73+</span></div><div><b>世界品種圖鑑</b><p>交換不同的真實貓咪，慢慢把世界圖鑑填滿。</p><div className="bar"><i/></div></div></div><div className="sectionTitle"><h2>最近遇見</h2><span>{incoming.length} cats</span></div><div className="catRow">{incoming.map((c,i)=><div className="miniCard" key={c.name}><div className={'catPhoto p'+i}>{c.emoji}</div><b>{c.name}</b><small>{c.place.split(',')[0]}</small></div>)}</div></section>}
 {tab==='snap'&&<section className="screen snapScreen">{!swapped?<><span className="eyebrow">DAILY STICKER · 01</span><h1>今天的 {active?.name}</h1><p className="lead">先拍下今天的樣子，再把這張貼紙送到世界某個人的圖鑑。</p><label className="upload"><input type="file" accept="image/*" capture="environment" onChange={choosePhoto}/><Camera size={22}/>{photo?'重新拍一張':'拍照或選擇照片'}</label><div className="stickerCard"><div className="tape">TODAY</div><div className="bigCat photoSlot">{photo?<img src={photo} alt="today cat"/>:'🐆'}</div><div className="stickerInfo"><div><span>#{(active?.breed||'CAT').toUpperCase()}</span><h2>{active?.name}</h2><p>{active?.place} · Today</p></div><Sparkles/></div><div className="rare">● COMMON · TODAY'S CAT</div></div><button className="primary" disabled={!photo} onClick={()=>setSwapped(true)}><RefreshCw size={20}/>送出去，交換一隻貓</button><small className="hint">MVP 目前先在你的手機模擬配對；下一階段才接真人資料庫。</small></>:<><span className="eyebrow">SWAP COMPLETE ✦</span><h1>有一隻貓來找你了！</h1><div className="stickerCard received"><div className="tape">NEW!</div><div className="bigCat">{today.emoji}</div><div className="stickerInfo"><div><span>#{today.breed.toUpperCase()}</span><h2>{today.name}</h2><p>{today.place}</p></div><Sparkles/></div><div className="rare">●● SPECIAL · {today.tag}</div></div><button className="primary" onClick={saveIncoming}><Sticker size={20}/>收進我的圖鑑</button><button className="textBtn" onClick={()=>{setSwapped(false);setPhoto('');setMatch((match+1)%incoming.length)}}>Demo：換下一個配對</button></>}</section>}
 {tab==='dex'&&<section className="screen"><span className="eyebrow">WORLD CATDEX</span><h1>世界貓咪圖鑑</h1><p className="lead">先用代表品種測試收藏體驗；正式版會改成完整 Breed + Variant 資料庫。</p><div className="dexGrid">{breeds.map(([en,zh,em],i)=><article className={discovered.has(en)?'found':''} key={en}><div>{discovered.has(en)?em:'?'}</div><span>#{String(i+1).padStart(3,'0')}</span><b>{zh}</b><small>{en}</small>{discovered.has(en)&&<i>DISCOVERED</i>}</article>)}</div></section>}
 {tab==='collection'&&<section className="screen"><span className="eyebrow">MY COLLECTION</span><h1>我遇見過的貓</h1><div className="stats"><div><b>{discovered.size}</b><span>Breeds</span></div><div><b>{saved.length}</b><span>Saved</span></div><div><b>3</b><span>Countries</span></div></div><div className="collection">{incoming.filter(c=>saved.includes(c.name)).map((c,i)=><div className="polaroid" key={c.name}><div className={'catPhoto p'+i}>{c.emoji}</div><b>{c.name}</b><span>{c.breed}</span><small>{c.place}</small></div>)}</div>{!saved.length&&<div className="notice"><Sticker/><div><b>收藏還是空的</b><p>拍下今日貓咪並完成第一次交換，就會得到第一張陌生貓貼紙。</p></div></div>}</section>}
 {tab==='profile'&&<section className="screen"><span className="eyebrow">MY CATS</span><h1>我的貓</h1>{cats.map((c,i)=><div className="myCat" key={c.name+i}><div>{c.photo?<img src={c.photo} alt={c.name}/>:'🐈'}</div><section><h2>{c.name}</h2><p>{c.breed}</p><span>{c.place}</span></section></div>)}<button className="primary" onClick={()=>setAdding(!adding)}><Plus size={20}/>新增我的貓</button>{adding&&<div className="formCard"><input placeholder="貓咪名字" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><select value={draft.breed} onChange={e=>setDraft({...draft,breed:e.target.value})}>{breeds.map(b=><option key={b[0]} value={b[0]}>{b[1]} · {b[0]}</option>)}</select><input placeholder="國家／城市" value={draft.place} onChange={e=>setDraft({...draft,place:e.target.value})}/><button className="primary" disabled={!draft.name} onClick={()=>{persist([...cats,draft]);setDraft({name:'',breed:'Domestic Shorthair',place:'Taiwan'});setAdding(false)}}>建立貓咪</button></div>}<div className="notice"><Cat/><div><b>米克斯也有自己的圖鑑位置</b><p>不需要猜血統。每一隻獨一無二的家貓，都可以交換、收藏與被世界看見。</p></div></div></section>}
 <nav>{[['home',Home,'首頁'],['dex',Globe2,'圖鑑'],['snap',Camera,'拍照'],['collection',Sticker,'收藏'],['profile',UserRound,'我的']].map(([id,Icon,label])=><button key={id as string} className={tab===id?'active':''} onClick={()=>setTab(id as Tab)}><Icon size={id==='snap'?25:21}/><span>{label as string}</span></button>)}</nav></main>
}